# Generated by Django 4.2.1 on 2023-05-12 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.OneToOneField(default=4, on_delete=django.db.models.deletion.PROTECT, to='accounts.usertype'),
            preserve_default=False,
        ),
    ]
