# Generated by Django 4.2.1 on 2023-05-15 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_product_favourite_productimage_color'),
        ('accounts', '0004_alter_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favourite',
            field=models.ManyToManyField(to='home.product'),
        ),
    ]
