# Generated by Django 4.2.1 on 2023-05-13 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_product_productcategory_productdata_productimage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ar_title',
        ),
        migrations.RemoveField(
            model_name='product',
            name='title',
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default=1, verbose_name='Product Description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='ar_description',
            field=models.TextField(blank=True, null=True, verbose_name='تفاصيل المنتج'),
        ),
    ]
