# Generated by Django 4.2.1 on 2023-05-15 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_product_ar_title_remove_product_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='favourite',
        ),
        migrations.AddField(
            model_name='productimage',
            name='color',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
