# Generated by Django 4.2.1 on 2023-05-15 02:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0004_remove_product_favourite_productimage_color'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productrate',
            unique_together={('user', 'product')},
        ),
        migrations.AlterIndexTogether(
            name='productrate',
            index_together={('user', 'product')},
        ),
    ]
